### ISSUE TITLE
validating the install

### ISSUE THREAD

**Issue by bmalic** [EarlRamirez/netdb#67]
Attempting to validate the install and receiving below:

netdbctl -ud -v
Cannot open /var/lock/netdb/netdbctl.lock at /usr/local/bin/netdbctl line 256.
[netdb@localhost root]$ netdbctl -a -m -debug 3
Mon Sep 16 23:15:07 2019: netdbctl(9063): NetDB Debug Level: 3
Cannot open /var/lock/netdb/netdbctl.lock at /usr/local/bin/netdbctl line 256.
[netdb@localhost root]$ ^
You have new mail in /var/spool/mail/root

**Comment by EarlRamirez** [comment]
@bmalic this means that the process is running, the scraper is scheduled to run every fifteen minutes as specified in /etc/crontab. To check if the running processes for netDB, run ` ps -ef | grep perl`
