### ISSUE TITLE
not working behind a corp firewall

### ISSUE THREAD

**Issue by callmejon** [EarlRamirez/netdb#69]
hi Earl, thanks for the netdb.
i try to install at home and work great. but once i have move the ova to office. the netdbctl process just got stuck.

is there any where in the netdb program need to access the internet? if do could you please show me where to remove the dependency?

thanks
JJ

**Comment by EarlRamirez** [comment]
@callmejon thank you very much for using netdb, there are no requirements for internet, can you add -vvv argument when you run the command? If the server that is hosting netdb is permitted to talk to your devices via SSH there should not be any issues.

**Comment by callmejon** [comment]
no device added in the list yet,

[netdb@localhost netdb]$ ./netdbctl.pl -ud -vv
Wed Nov  6 00:01:01 2019: netdbctl(17434): NetDB Debug Level: 3
Cannot open /var/lock/netdb/netdbctl.lock at ./netdbctl.pl line 256.
[netdb@localhost netdb]$

**Comment by callmejon** [comment]
its working fine at home, but when i export the ova and put in work PC it got stuck.

**Comment by EarlRamirez** [comment]
> no device added in the list yet,
>
Add at least one device to the devicelist

> [netdb@localhost netdb]$ ./netdbctl.pl -ud -vv
> Wed Nov 6 00:01:01 2019: netdbctl(17434): NetDB Debug Level: 3
> Cannot open /var/lock/netdb/netdbctl.lock at ./netdbctl.pl line 256.
> [netdb@localhost netdb]$
>
Can you run the following commands
mkdir -p /var/lock/netdb
chown netdb /var/lock/netdb

**Comment by callmejon** [comment]
very nice :) worked again..

**Comment by callmejon** [comment]
thanks for your help!!!

**Comment by EarlRamirez** [comment]
Glad that it worked
