### ISSUE TITLE
Would be nice if this or some clone of this continued to be actively developed

### ISSUE THREAD

**Issue by StewAlexander-com** [EarlRamirez/netdb#80]
At the moment we are using ```NetDisco``` a nice tool, although a bit clunky in implementation... Docker is easier to setup

We need a tool to view changes to switch ports over time ... 

time 0 gi3/0/2  was this
time 1 gi 3/0/2 changed to this
time 2 gi 3/0/2 reverted back to time 0 

etc

Nothing appears to do this, oddly

**Comment by EarlRamirez** [comment]
> time 0 gi3/0/2 was this
> time 1 gi 3/0/2 changed to this
> time 2 gi 3/0/2 reverted back to time 0

At the back of my head, a NAC (Network Access Control) does what you want. I will admit that I haven't invested sufficient time in tis project; however, I have started to work on the roadmap. 

I will definitely look into the historical states.

Thanks

**Comment by StewAlexander-com** [comment]
Thanks!
